# Generated by Django 3.2.6 on 2021-10-07 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='customer_rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Đánh giá nhỏ hơn hoặc bằng 5'), django.core.validators.MinValueValidator(limit_value=1, message='Đánh giá từ 1 đến 5')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='shipper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rate_shiper', to=settings.AUTH_USER_MODEL),
        ),
    ]
