# Generated by Django 3.2.6 on 2021-08-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordership',
            name='shipper',
        ),
    ]
