# Generated by Django 3.2.6 on 2021-08-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='receive_adress',
        ),
        migrations.RemoveField(
            model_name='post',
            name='send_adress',
        ),
    ]
