# Generated by Django 3.2.6 on 2021-08-09 14:10

import abaShip.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('percent', models.FloatField(validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ordership',
            name='send_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_ship_send', to='abaShip.stock'),
        ),
        migrations.CreateModel(
            name='DetpApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_payed', models.BooleanField(default=False)),
                ('pay_method', models.CharField(choices=[(abaShip.models.PayMethod['ZALO'], 'ZALO'), (abaShip.models.PayMethod['MOMO'], 'MOMO'), (abaShip.models.PayMethod['TIENMAT'], 'TIENMAT')], max_length=20)),
                ('deduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abaShip.deduct')),
                ('order_ship', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abaShip.ordership')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebtShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_payed', models.BooleanField(default=False)),
                ('deduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abaShip.deduct')),
                ('order_ship', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abaShip.ordership')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
