# Generated by Django 3.2.6 on 2021-08-10 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0002_auto_20210809_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='deduct',
            name='percent',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(40.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='image_card',
            field=models.ImageField(upload_to='idcard/%Y/%m'),
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item/%Y/%m')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abaShip.post')),
            ],
        ),
    ]
