# Generated by Django 3.2.6 on 2021-09-17 13:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0002_auto_20210916_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('rate', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Đánh giá nhỏ hơn hoặc bằng 5'), django.core.validators.MinValueValidator(limit_value=1, message='đánh giá từ 1 đến 5')])),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='shipper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'shipper')},
            },
        ),
        migrations.DeleteModel(
            name='CommentShipper',
        ),
    ]
