# Generated by Django 3.2.6 on 2021-08-19 15:30

import abaShip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0002_auto_20210819_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordership',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'shipped'), ('SHIPPING', 'shipping'), ('NOTYETSHIPPED', 'not yet shipped')], default=abaShip.models.StatusShip['NOTYETSHIPPED'], max_length=30),
        ),
    ]
