# Generated by Django 3.2.6 on 2021-08-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0002_remove_ordership_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordership',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'shipped'), ('SHIPPING', 'shipping'), ('NOTYETSHIPPED', 'not yet shipped')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordershipdetail',
            name='orderShip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abaShip.ordership'),
        ),
    ]
