# Generated by Django 3.2.6 on 2021-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0002_auto_20211007_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordership',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordership',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
