# Generated by Django 3.2.6 on 2021-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0003_auto_20210810_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
