# Generated by Django 3.2.6 on 2021-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0003_auto_20211009_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordership',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
