# Generated by Django 3.2.6 on 2021-08-19 15:46

import abaShip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0003_alter_ordership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordership',
            name='shipped_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordership',
            name='status',
            field=models.CharField(choices=[('NOTYETSHIPPED', 'not yet shipped'), ('SHIPPING', 'shipping'), ('SHIPPED', 'shipped')], default=abaShip.models.StatusShip['NOTYETSHIPPED'], max_length=30),
        ),
    ]
