# Generated by Django 3.2.6 on 2021-08-26 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0004_auto_20210819_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_items', to='abaShip.post'),
        ),
        migrations.AlterField(
            model_name='ordership',
            name='auction_win',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='order_ship', serialize=False, to='abaShip.auction'),
        ),
        migrations.AlterField(
            model_name='ordership',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
