# Generated by Django 3.2.6 on 2021-08-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0004_auto_20210810_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='decription',
            new_name='description',
        ),
    ]
