# Generated by Django 3.2.6 on 2021-09-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0004_auto_20210917_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='active',
        ),
    ]
