# Generated by Django 3.2.6 on 2021-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0005_remove_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
