# Generated by Django 3.2.6 on 2021-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0005_rename_decription_voucher_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='image_card',
        ),
        migrations.AddField(
            model_name='idcard',
            name='image_card_back',
            field=models.ImageField(default=None, upload_to='idcard/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='image_card_front',
            field=models.ImageField(default=None, upload_to='idcard/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='item/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar/%Y/%m/'),
        ),
    ]
