# Generated by Django 3.2.6 on 2021-08-15 08:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0006_auto_20210812_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordership',
            name='auction_win',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='abaShip.auction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
