# Generated by Django 3.2.6 on 2021-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0006_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordership',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not yet shipped'), (1, 'shipping'), (2, 'shipped')], default=0),
        ),
    ]
