# Generated by Django 3.2.6 on 2021-08-27 15:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='image_card_back',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_card_back'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='image_card_front',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_card_front'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
