# Generated by Django 3.2.6 on 2021-08-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0007_auto_20210815_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordership',
            name='auction_win',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abaShip.auction'),
        ),
    ]
