# Generated by Django 3.2.6 on 2021-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0008_alter_ordership_auction_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
        migrations.AddField(
            model_name='auction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=14),
        ),
    ]
