# Generated by Django 3.2.6 on 2021-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0008_alter_ordershipdetail_pay_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordership',
            name='status',
        ),
        migrations.AlterField(
            model_name='ordershipdetail',
            name='pay_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zalo pay'), (1, 'Momo'), (2, 'Cash')], default=2),
        ),
    ]
