# Generated by Django 3.2.6 on 2021-08-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0009_auto_20210815_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
