# Generated by Django 3.2.6 on 2021-08-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abaShip', '0011_rename_active_auction_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetpApp',
            new_name='DebtApp',
        ),
    ]
